### ISSUE TITLE
Add installation module 

### ISSUE THREAD

**Issue by SamiEzz** [dilovanmatini/duhok-forum#2]
Hello Dilovan,
I think that many potentiel users of  Duhok-Forum, may feel intimidated by the php code. 
This could be a first obstacle that stop people from using this software. 
That's why an installation module that automate this modifications will avoid this obstacle.
I will open a pull request to do the fix.

**Comment by dilovanmatini** [comment]
Hello Mr. Sami,

Thanks for your precious comments,
PHP has strong security same other programming languages, but when developers coding on this language, they should think of everything they do, including how to secure their codes. Therefore, don't worry about PHP. I am sure someday Duhok Forum will be one of the most securable scripts in the world.

Best Regards,
