### ISSUE TITLE
Release 3.0 minor fix

### ISSUE THREAD

**Issue by SamiEzz** [dilovanmatini/duhok-forum#3]
https://github.com/dilovanmatini/duhok-forum/blob/c24a9ba0336270734ffb30011173baed042a6a55/includes/class.html.php#L19

Please fix this minor issue that prevent any use of the software. 
[I checked only in release 3.0]

**Comment by dilovanmatini** [comment]
> https://github.com/dilovanmatini/duhok-forum/blob/c24a9ba0336270734ffb30011173baed042a6a55/includes/class.html.php#L19
> 
> Please fix this minor issue that prevent any use of the software.
> [I checked only in release 3.0]

The issue has been resolved.
Thanks for your cooperation.
